# Generated by Django 5.1.6 on 2025-02-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airports',
            new_name='Airport',
        ),
    ]
